// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Ofichina.Infrastructure.Persistence;

#nullable disable

namespace Ofichina.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260716040000_003-servicos")]
partial class _003servicos
{
}
