// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Ofichina.Infrastructure.Persistence;

#nullable disable

namespace Ofichina.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260716050000_004-item-servico-servicoid")]
partial class _004itemservicoservicoid
{
}
