version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ofichina-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd2024!Ofichina"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    restart: unless-stopped

    networks:
      - ofichina-network

  postgres:
    image: postgres:16
    container_name: sonarqube-postgres

    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

    networks:
      - ofichina-network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube

    depends_on:
      - postgres

    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube

    ports:
      - "9000:9000"

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

    restart: unless-stopped

    networks:
      - ofichina-network

  seq:
    image: datalust/seq:latest
    container_name: ofichina-seq

    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "Admin123@"

    ports:
      - "5341:80"

    volumes:
      - seq_data:/data

    restart: unless-stopped

    networks:
      - ofichina-network

volumes:
  sqlserver_data:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  seq_data:

networks:
  ofichina-network:
    driver: bridge