<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ofichina.Application\Ofichina.Application.csproj" />
    <ProjectReference Include="..\Ofichina.Infrastructure\Ofichina.Infrastructure.csproj" />
    <ProjectReference Include="..\Ofichina.Authentication\Ofichina.Authentication.csproj" />
  </ItemGroup>

</Project>
